### ISSUE TITLE
Add linebreak-style 'windows' to .eslintrc.js

### ISSUE THREAD

**Issue by SonSon0815** [JaydenUlysses/Olaf-the-coolest-of-Bots#2]
Bei mir wurden ALLE Zeilen in .js files als fehlerhaft markiert, da der Zeilenumbruch als CRLF statt LF erkannt wurde (scheint Windows Standard zu sein, CRLF zu setzen).
Da das ziemlich nervig war, habe ich lokal das .eslintrc.js File nochmal neu initialisiert und angepasst.
Der (ich vermute mal) Workaround über .gitattributes hat keinen Effekt gehabt und ich halte diesen nicht für sinnvoll.
Vorschlag für .eslintrc.js (für ganzes Projekt):

```
rules: {
  'linebreak-style': ['error', 'windows']
}
```
Damit hat ESLint keine Fehler mehr erzeugt.

**Comment by kiephil** [comment]
Ich werde das Feature ausstellen, da Linebreaks für uns keine Auswirkungen haben "sollten"

Geht zum Glück sehr einfach durch `'linebreak-style': 0`

**Comment by DominikStiller** [comment]
Hat aber Auswirkungen, sobald man zwei Personen mit unterscheidlichen Linebreak-Settings an der gleichen Datei arbeiten. Dann gibts Pseudo-Diffs wo nur die Lineendings anders sind.
Allgemeine Praxis ist eigentlich LF, auch auf Windows. Also ich würde das schon enforcen.
